name: Test UI

on:
  workflow_dispatch:

jobs:
 test-ubuntu:
    name: Build the repository on Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Make sure build is clean and no files from a previous run are re-used.
      - name: Cleanup files before run
        run: |
          rm -rf *
        if: ${{ always() }}

      - name: Checkout
        uses: actions/checkout@v3.2.0
        
      - name: Use Node.js 20
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install node packages
        run: yarn install

      - name: Install dpkg, fakeroot and rpm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dpkg fakeroot rpm libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libgtk-3-0 libpango-1.0-0 libcairo2 libgdk-pixbuf2.0-0 libgbm1 libasound2 libatspi2.0-0

      - name: Provide 777 execution rights to clipboard handler script
        run: |
          sudo chmod 777 node_modules/clipboard-event/platform/clipboard-event-handler-linux

      - name: Set envionment variables
        run: |
          export JAPREADER_ENV=playwright
          export NODE_ENV=development
          export CLEAR_TOKENS=true
          export JAPREADER_LOGS=silly
          export PLAYWRIGHT=true
          export DEBUG=pw:browser*,pw:api
          export DEBUG_FILE=playwright.log

      - name: Package
        run: yarn package
      
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          options: -screen 0 1280x960x24
          run: yarn test:ui

      - name: Tree list the runner
        if: always()
        run: tree . -I 'node_modules|src|images|'

      - name: Copy test artifacts into the common folder
        if: always()
        run: | 
          mv playwright.log test-results/
          mv webm/ test-results/

      - name: Upload a Test Artifact
        if: always()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: playwright-output
          path: test-results
          retention-days: 28
