name: Test UI

on:
  workflow_dispatch:

jobs:
 test-ubuntu:
    name: Build the repository on Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Make sure build is clean and no files from a previous run are re-used.
      - name: Cleanup files before run
        run: |
          rm -rf *
        if: ${{ always() }}

      - name: Checkout
        uses: actions/checkout@v3.2.0
        
      - name: Use Node.js 20
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install node packages
        run: yarn install

      - name: Install dpkg, fakeroot and rpm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dpkg fakeroot rpm libatk-bridge2.0-0 libgtk-3.0 libasound2

      - name: Provide 777 execution rights to clipboard handler script
        run: |
          sudo chmod 777 node_modules/clipboard-event/platform/clipboard-event-handler-linux
      - name: Set JAPREADER_ENV to 'production'
        run: export JAPREADER_ENV=production
        
      - name: Set NODE_ENV to 'production'
        run: export NODE_ENV=production

      - name: Package
        run: yarn package
      
      - run: tree out/
      
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          run: DEBUG=pw:browser* yarn test:ui

      - run: tree out/

      - name: Upload a Test Artifact
        if: always()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: playwright-output
          path: test-results
          retention-days: 28
